backend:
  name: git-gateway
  branch: main # nebo "master", podle toho co máš ve skutečnosti

media_folder: "images" # kam se ukládají obrázky v repozitáři
public_folder: "/images" # jak se obrázky odkazují z webu

collections:
  - name: "posts"
    label: "Články"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Ondra" }
      - { label: "Shrnutí", name: "summary", widget: "text" }
      - { label: "Tagy", name: "tags", widget: "list" }
      - { label: "Hero obrázek", name: "hero", widget: "image" }
      - { label: "Obsah", name: "body", widget: "markdown" }

